serve:
    browser: false
sources:
    - name: gRPC Example
      handler:
          grpc:
              # source: proto/playground.proto
              source: graphql-schema/schema.graphql
              endpoint: localhost:5210
